### ISSUE TITLE
`pyproject.toml` support

### ISSUE THREAD

**Issue by Olegt0rr** [jpetrucciani/mypy-check#23]
Please, add `pyproject.toml` support

**Comment by mscheltienne** [comment]
+1 for this!

**Comment by mscheltienne** [comment]
Is it actually not supported?

```
      - name: Run mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: './mne_icalabel'
          mypy_flags: '--config-file pyproject.toml'
```

That seems to work fine.
