### ISSUE TITLE
There are no .py[i] files in directory '.'

### ISSUE THREAD

**Issue by danieleades** [jpetrucciani/mypy-check#3]
i'm using the `.mypy.ini` config file to specify which files to include when running mypy (such that I can simply run `$ mypy`. I'm also using this config file to exclude particular files and directories.

if i use this action without any arguments i get this error-

```
There are no .py[i] files in directory '.'
```

how should i be using this?

**Comment by pfandzelter** [comment]
I was able to fix this by using `path: "*.py"` like so:

```yaml
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MyPy Check
        uses: jpetrucciani/mypy-check@master
        with:
          path: "*.py"
```
